# Branches with names starting with `example` are meant to be long living branches used as
# documentation/usage example.
# After accepting the branch, the main PR should be closed
on:
  pull_request

jobs:
  label-example-branch:
    name: Add example label to the PR
    # if: ${{ startsWith(github.ref, 'refs/heads/example') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Deploying to production server on branch $GITHUB_REF_NAME"
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            example

  block-example-merging:
    name: Example branches are not meant to be merged
    runs-on: ubuntu-latest
    steps:
      - name: Prevent example branches from merging
        run: |
          echo "Example branches are not meant to be merged"
          exit 1