# Branches with names starting with `example` are meant to be long living branches used as
# documentation/usage example.
# After accepting the branch, the main PR should be closed
on:
  pull_request:
    branches:
      - 'example**'
jobs:
  label-example-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            example

  block-example-merging:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent example branches from merging
        run: |
          echo "Example branches are not meant to be merged"
          exit 1